import { Geist, Geist_Mono, Libre_Baskerville, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/site/header";
import Footer from "@/components/site/footer";
import Inquiry from "@/components/site/inquiry";
import OverscreenInquiryButton from "@/components/site/overscreen-inquiry-button";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libreBaskerville",
  subsets: ["latin"],
  weight:["400", "700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${montserrat.variable} ${libreBaskerville.variable} antialiased flex flex-col min-h-screen`}
      >
        <OverscreenInquiryButton />
        <Header />
        <div className="flex-1">
          {children}
        </div>
        <Inquiry />
        <Footer />
      </body>
    </html>
  );
}
